In [7]:
#Task 1
import numpy as np
arr=np.array([[1,2,3,4],[10,11,12,13]], dtype=float)
print(arr.astype(bool))

[[ True  True  True  True]
 [ True  True  True  True]]


In [9]:
#Task 2
import numpy as np
arr=np.array([1,2,3,4])
arr0=np.insert(arr,2,55)
print(arr)
print(arr0)

[1 2 3 4]
[ 1  2 55  3  4]


In [24]:
#Task 3
import numpy as np
arr=np.arange(0,100,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [13]:
#Task 4
import numpy as np
arr=np.array([2,3,5,7])
arr0=np.array([4,6,9,11])
arr1=np.dot(arr,arr0) # By DOt Method
arr2=arr*arr0 # By simple Multiply
print(arr1)
print(arr2)

148
[ 8 18 45 77]


In [41]:
#Task 5
array=[3,5,7,9,11]
num=int(input("Enter any number to check: "))

for number in array:
    if number == num:
        print(f"{num} is present in the array.")
        break
else:
    print(f"{num} is not present in the array.")

Enter any number to check: 3
3 is present in the array.
